//! A throwaway, private `CODEX_HOME` for a single operation, holding only a minimal `config.toml`
//! (nothing is copied from the user's home). A `Drop` guard removes it; a killed process skips
//! the guard, so [`sweep_stale`] clears leftovers at start-up.

use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use super::permissions;
use crate::diagnostics::{
    ErrorCode, Phase, Result, TogletError, UserAction, record_background_failure,
};

/// The entire `config.toml` of an isolated home. The file credential store keeps the app server
/// reading `auth.json` from this directory rather than somewhere Toglet does not control.
const MINIMAL_CONFIG: &str = "\
# Minimal Codex home generated by Toglet for a single isolated operation.
# Only the credential store mode is set - nothing is copied from the user's own configuration.
cli_auth_credentials_store = \"file\"
";

/// Prefix of every isolated home's name; the sweep touches nothing else.
const NAME_PREFIX: &str = "toglet-";

/// How long a home must be untouched before a sweep removes it. Generous because another
/// running Toglet instance may still be using it.
const STALE_AFTER: std::time::Duration = std::time::Duration::from_secs(60 * 60);

/// Retries for a directory name that is not already taken. A collision is not an error worth
/// surfacing, but an endless loop would be.
const NAME_ATTEMPTS: u32 = 8;

static SEQUENCE: AtomicU64 = AtomicU64::new(0);

/// An isolated `CODEX_HOME` that deletes itself.
pub struct IsolatedHome {
    path: PathBuf,
    /// The operation this home belongs to, so cleanup failures name the right step.
    phase: Phase,
    /// Set by [`IsolatedHome::cleanup`] so the guard does not run a second time.
    disarmed: bool,
}

impl IsolatedHome {
    /// Creates a private directory holding the minimal `config.toml`. `phase` names the operation
    /// in any failure.
    pub fn create(phase: Phase) -> Result<Self> {
        let root = std::env::temp_dir();

        for _ in 0..NAME_ATTEMPTS {
            let candidate = root.join(format!("toglet-{}", unique_name()));
            match permissions::create_private_dir(&candidate) {
                Ok(()) => {
                    // Guard is armed from here on: if writing the config fails, `home` is
                    // dropped on the way out and the directory goes with it.
                    let home = Self {
                        path: candidate,
                        phase,
                        disarmed: false,
                    };
                    permissions::write_private_file(
                        &home.path.join("config.toml"),
                        MINIMAL_CONFIG.as_bytes(),
                    )
                    .map_err(|error| unwritable(phase, &error.to_string()))?;
                    return Ok(home);
                }
                // Somebody else owns that name. Never adopt an existing directory: its
                // permissions and contents are unknown.
                Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
                Err(error) => return Err(unwritable(phase, &error.to_string())),
            }
        }

        Err(unwritable(
            phase,
            "no unused name for the isolated home directory",
        ))
    }

    /// The directory to pass as `CODEX_HOME`.
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// The operation this home was created for; everything inside it reports against this phase.
    pub fn phase(&self) -> Phase {
        self.phase
    }

    /// Deletes the directory and reports the result, which the guard cannot return.
    pub fn cleanup(mut self) -> Result<()> {
        self.disarmed = true;
        self.remove()
    }

    fn remove(&self) -> Result<()> {
        match std::fs::remove_dir_all(&self.path) {
            Ok(()) => Ok(()),
            // The app server creates `.personality_migration`, `skills` and `tmp` here, so
            // removal is recursive; already gone is not a failure.
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(error) => Err(unwritable(self.phase, &error.to_string())),
        }
    }
}

/// Removes isolated homes a killed run left behind (they may hold a decrypted `auth.json`) and
/// returns how many went. Called once at start-up.
///
/// Deliberately narrow: only in the temporary directory, only `toglet-` names, only entries
/// untouched for [`STALE_AFTER`]. Failures are skipped so start-up is never blocked.
pub fn sweep_stale() -> usize {
    let root = std::env::temp_dir();
    let Ok(entries) = std::fs::read_dir(&root) else {
        return 0;
    };

    let mut removed = 0;
    for entry in entries.flatten() {
        if !is_stale_home(&entry) {
            continue;
        }
        if std::fs::remove_dir_all(entry.path()).is_ok() {
            removed += 1;
        }
    }
    removed
}

fn is_stale_home(entry: &std::fs::DirEntry) -> bool {
    let metadata = entry.metadata().ok();
    is_stale(
        &entry.file_name().to_string_lossy(),
        metadata.as_ref().is_some_and(std::fs::Metadata::is_dir),
        metadata
            .as_ref()
            .and_then(|data| data.modified().ok())
            .and_then(|at| at.elapsed().ok()),
    )
}

/// Whether an entry may be removed; kept free of the filesystem so the rule can be tested.
fn is_stale(name: &str, is_dir: bool, age: Option<std::time::Duration>) -> bool {
    // An unreadable or future-dated timestamp is not stale: never delete on no evidence.
    name.starts_with(NAME_PREFIX) && is_dir && age.is_some_and(|age| age >= STALE_AFTER)
}

impl Drop for IsolatedHome {
    fn drop(&mut self) {
        if self.disarmed {
            return;
        }
        if let Err(error) = self.remove() {
            // Cannot return or panic here, so record it. The leftover is still user-only.
            record_background_failure(error);
        }
    }
}

fn unwritable(phase: Phase, detail: &str) -> TogletError {
    TogletError::new(
        ErrorCode::CodexHomeUnwritable,
        phase,
        true,
        UserAction::Retry,
    )
    .with_detail(detail)
}

/// The directory an app server runs against.
/// Separate variants because `IsolatedHome` deletes its directory on drop; `Default` owns no
/// cleanup, so the user's real home can never be removed.
pub enum ServerHome {
    /// A throwaway directory, removed when this value is dropped.
    Isolated(IsolatedHome),
    /// The user's own Codex home. Never deleted.
    Default { path: PathBuf, phase: Phase },
}

impl ServerHome {
    /// The directory to pass as `CODEX_HOME`.
    pub fn path(&self) -> &Path {
        match self {
            Self::Isolated(home) => home.path(),
            Self::Default { path, .. } => path,
        }
    }

    /// The operation this home is being used for.
    pub fn phase(&self) -> Phase {
        match self {
            Self::Isolated(home) => home.phase(),
            Self::Default { phase, .. } => *phase,
        }
    }

    /// Whether this is the user's real Codex home.
    pub fn is_default(&self) -> bool {
        matches!(self, Self::Default { .. })
    }
}

impl From<IsolatedHome> for ServerHome {
    fn from(home: IsolatedHome) -> Self {
        Self::Isolated(home)
    }
}

/// A name unlikely to be taken. Not a security measure: creation fails if the name exists.
fn unique_name() -> String {
    use std::collections::hash_map::RandomState;
    use std::hash::{BuildHasher, Hasher};

    let mut hasher = RandomState::new().build_hasher();
    hasher.write_u32(std::process::id());
    hasher.write_u64(SEQUENCE.fetch_add(1, Ordering::Relaxed));
    format!("{:016x}", hasher.finish())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config_path(home: &IsolatedHome) -> PathBuf {
        home.path().join("config.toml")
    }

    #[test]
    fn directory_and_config_are_readable_by_the_current_user_only() {
        let home = IsolatedHome::create(Phase::ReadQuota).expect("home is created");

        permissions::assert_private(home.path());
        permissions::assert_private(&config_path(&home));
    }

    #[test]
    fn config_sets_the_credential_store_and_nothing_else() {
        let home = IsolatedHome::create(Phase::ReadQuota).expect("home is created");

        let config = std::fs::read_to_string(config_path(&home)).expect("config is readable");
        let settings: Vec<&str> = config
            .lines()
            .map(str::trim)
            .filter(|line| !line.is_empty() && !line.starts_with('#'))
            .collect();

        assert_eq!(settings, vec![r#"cli_auth_credentials_store = "file""#]);
    }

    #[test]
    fn nothing_is_copied_from_the_users_home() {
        let home = IsolatedHome::create(Phase::ReadQuota).expect("home is created");

        let entries: Vec<String> = std::fs::read_dir(home.path())
            .expect("home is readable")
            .map(|entry| entry.expect("entry is readable").file_name())
            .map(|name| name.to_string_lossy().into_owned())
            .collect();

        assert_eq!(entries, vec!["config.toml".to_owned()]);
    }

    #[test]
    fn explicit_cleanup_removes_the_directory() {
        let home = IsolatedHome::create(Phase::Login).expect("home is created");
        let path = home.path().to_path_buf();

        home.cleanup().expect("cleanup succeeds");

        assert!(!path.exists());
    }

    #[test]
    fn cleanup_is_recursive() {
        let home = IsolatedHome::create(Phase::ReadQuota).expect("home is created");
        let path = home.path().to_path_buf();
        // What the app server was observed to leave behind in an isolated home.
        for leftover in [".personality_migration", "skills", "tmp"] {
            std::fs::create_dir(path.join(leftover)).expect("leftover directory is created");
            std::fs::write(path.join(leftover).join("data"), b"x").expect("leftover file written");
        }

        drop(home);

        assert!(!path.exists());
    }

    #[test]
    fn guard_removes_the_directory_when_the_caller_returns_early() {
        // Stands in for a precheck that fails after the home exists: the caller returns
        // without ever reaching a cleanup call.
        fn abandon_after_creating(observed: &mut PathBuf) -> Result<()> {
            let home = IsolatedHome::create(Phase::ReadQuota)?;
            *observed = home.path().to_path_buf();
            Err(unwritable(Phase::ReadQuota, "simulated early return"))
        }

        let mut path = PathBuf::new();
        assert!(abandon_after_creating(&mut path).is_err());
        assert!(!path.as_os_str().is_empty());
        assert!(!path.exists());
    }

    #[test]
    fn guard_removes_the_directory_when_the_caller_panics() {
        let path = std::sync::Arc::new(std::sync::Mutex::new(PathBuf::new()));
        let recorded = std::sync::Arc::clone(&path);

        let result = std::panic::catch_unwind(move || {
            let home = IsolatedHome::create(Phase::ReadQuota).expect("home is created");
            *recorded.lock().expect("lock is available") = home.path().to_path_buf();
            panic!("simulated failure while the home is in use");
        });

        assert!(result.is_err());
        let path = path.lock().expect("lock is available").clone();
        assert!(!path.as_os_str().is_empty());
        assert!(!path.exists());
    }

    #[test]
    fn two_homes_do_not_share_a_directory() {
        let first = IsolatedHome::create(Phase::ReadQuota).expect("first home is created");
        let second = IsolatedHome::create(Phase::ReadQuota).expect("second home is created");

        assert_ne!(first.path(), second.path());
    }

    /// Uses explicit `cleanup()`: the guard passes the same error to `record_background_failure`,
    /// whose process-wide buffer other tests also write to.
    #[cfg(windows)]
    #[test]
    fn a_cleanup_that_cannot_succeed_reports_a_redacted_error() {
        use std::os::windows::fs::OpenOptionsExt;

        let home = IsolatedHome::create(Phase::ReadQuota).expect("home is created");
        let path = home.path().to_path_buf();
        // Share mode 0 makes the file undeletable until this handle closes, which is the
        // simplest way to make removal fail for real rather than by mocking it.
        let blocker = std::fs::OpenOptions::new()
            .read(true)
            .share_mode(0)
            .open(config_path(&home))
            .expect("config is openable");

        let error = home
            .cleanup()
            .expect_err("removal cannot succeed while the file is held");

        assert_eq!(error.code(), ErrorCode::CodexHomeUnwritable);
        assert_eq!(error.phase(), Phase::ReadQuota);
        let detail = error.detail().expect("the failure carries detail");
        assert!(!detail.contains(r"C:\"), "the detail must not carry a path");

        drop(blocker);
        drop(std::fs::remove_dir_all(&path));
    }

    /// The sweep deletes directories in a shared temporary folder, so the tests are almost
    /// entirely about what it refuses to touch.
    mod sweeping {
        use super::*;
        use std::time::Duration;

        const OLD: Option<Duration> = Some(Duration::from_secs(60 * 60 * 24));
        const FRESH: Option<Duration> = Some(Duration::from_secs(5));

        #[test]
        fn removes_a_home_an_earlier_run_left_behind() {
            assert!(is_stale("toglet-abcdef", true, OLD));
        }

        #[test]
        fn leaves_a_home_that_is_still_in_use_alone() {
            // A running Toglet holds this one, and a second instance is possible. The
            // age is the only thing standing between the sweep and somebody else's live home.
            assert!(!is_stale("toglet-abcdef", true, FRESH));
        }

        #[test]
        fn never_touches_a_directory_that_is_not_one_of_ours() {
            // The temporary directory is shared with every other program on the machine.
            assert!(!is_stale("not-toglet", true, OLD));
            assert!(!is_stale("codex-something", true, OLD));
            assert!(!is_stale("", true, OLD));
        }

        #[test]
        fn never_removes_anything_that_is_not_a_directory() {
            assert!(!is_stale("toglet-abcdef", false, OLD));
        }

        #[test]
        fn treats_an_unreadable_age_as_still_in_use() {
            // Deleting on no evidence at all is the one outcome that cannot be undone.
            assert!(!is_stale("toglet-abcdef", true, None));
        }

        #[test]
        fn does_not_remove_a_home_that_is_in_use_right_now() {
            // The one test that runs the real sweep: it must be safe to call while a home is
            // open, which is exactly what start-up does.
            let home = IsolatedHome::create(Phase::ReadQuota).expect("created");
            let path = home.path().to_path_buf();

            sweep_stale();

            assert!(path.exists(), "a home in use was removed");
        }
    }
}
