#!/usr/bin/env bash
# Packs the bridge deployment into one self-extracting script. NOT PART OF TOGLET - see README.md.
#
#   ./pack.sh                 writes ./toglet-bridge-install.sh
#   scp toglet-bridge-install.sh root@server:
#   ssh root@server 'bash toglet-bridge-install.sh bridge.example.com'
#
# The release workflow attaches the result to each GitHub release. The payload is a tar of the
# files listed below, rebuilt on every run.

set -euo pipefail
cd "$(dirname "$0")"

OUT="${1:-toglet-bridge-install.sh}"

FILES=(
  remote-bridge/bridge.mjs
  remote-bridge/compose.yaml
  remote-bridge/Caddyfile
  remote-bridge/up.sh
  pwa/index.html
  pwa/app.js
  pwa/sw.js
  pwa/manifest.webmanifest
  pwa/icon.svg
)
for f in "${FILES[@]}"; do
  [[ -f "$f" ]] || { printf 'missing: %s\n' "$f" >&2; exit 1; }
done

{
  cat <<'HEAD'
#!/usr/bin/env bash
# Toglet remote bridge - self-extracting deployment. NOT PART OF TOGLET.
#
#   bash toglet-bridge-install.sh                         asks for the domain
#   bash toglet-bridge-install.sh bridge.example.com      asks only for the path prefix
#   bash toglet-bridge-install.sh bridge.example.com a1b2 asks nothing
#
#   curl -fsSL https://…/toglet-bridge-install.sh | bash -s -- bridge.example.com
#
#   TOGLET_DIR=/srv/toglet bash toglet-bridge-install.sh  unpack somewhere else
#
# Generated by examples/pack.sh - do not edit. Unpacks the files and runs up.sh, which writes
# .env and starts the stack. Everything afterwards is plain `docker compose`.

set -euo pipefail

DIR="${TOGLET_DIR:-/opt/toglet}"

# `base64 -d` on coreutils, `-D` on BSD. openssl is the fallback for the machines with neither.
decode() {
  if base64 -d </dev/null >/dev/null 2>&1; then base64 -d
  elif base64 -D </dev/null >/dev/null 2>&1; then base64 -D
  else openssl base64 -d
  fi
}

# As a file, the payload is read from $0. Piped in, bash reads stdin one byte at a time, so the
# rest of stdin is the payload.
payload() {
  if [[ -f "$0" ]] && grep -q '^#PAYLOAD$' "$0" 2>/dev/null; then
    sed -n '/^#PAYLOAD$/,$p' "$0"
  else
    sed -n '/^#PAYLOAD$/,$p'
  fi | tail -n +2
}

# One function on purpose: when piped, draining stdin leaves bash nothing more to read, so
# everything that runs afterwards must already be parsed.
main() {
  mkdir -p "$DIR"
  payload | decode | tar -xzf - -C "$DIR"
  printf 'Unpacked into %s\n' "$DIR"

  cd "$DIR/remote-bridge"
  chmod +x up.sh
  exec ./up.sh "$@"
}

main "$@"
HEAD
  printf '\nexit 0\n#PAYLOAD\n'
  tar -czf - "${FILES[@]}" | base64
} > "$OUT"

chmod +x "$OUT"
printf 'wrote %s (%s)\n' "$OUT" "$(du -h "$OUT" | cut -f1)"
